services:
  research:
    build: .
    volumes:
      - ./data:/app/data  # ホストの data フォルダをコンテナにマウント
    working_dir: /app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: replication_db
      POSTGRES_USER: replication_user
      POSTGRES_PASSWORD: replication_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
